### ISSUE TITLE
Missing brightness control

### ISSUE THREAD

**Issue by zipotron** [piggz/harbour-advanced-camera#112]
Hi, I am missing gesture brightness control for photo or during recording video. Thanks

**Comment by Karry** [comment]
Hi. I tried to change   `exposure.exposureCompensation` of QML `Camera` instance and it seems to be working, at least on Xperia 10 II. So the only missing part is the UI for changing this property.

**Comment by zipotron** [comment]
Hi! Great Karry!

**Comment by Karry** [comment]
You close the ticket too early. I just verify that implementation would be easy just in QML, but I don't implement it yet ;-)
