### ISSUE TITLE
SFOS 4.4.0.58 - not working again

### ISSUE THREAD

**Issue by cy8aer** [piggz/harbour-advanced-camera#129]
Looks like ghe gstreamer error occurs again with SFOS 4.4.0.58

```
[D] applySettings:738 - Applying settings in image mode for 0 camera with status 8
[W] unknown:0 - CameraBin error: "GStreamer encountered a general supporting library error."
```

**Comment by Karry** [comment]
It is working for me, on Xperia 10 II, SFOS 4.4.0.58. What device do you have?

**Comment by cy8aer** [comment]
hm, I screwed up my repository settings and installed an old version somehow. Reinstalled the newest version of advanced camera again - and it is working. I close this bug.
