### ISSUE TITLE
Color Issues and hanging app

### ISSUE THREAD

**Issue by bonanza123** [piggz/harbour-advanced-camera#49]
On my XA2 Ultra with v17b binaries, the app is working for like 1sec and produces this previews: https://i.imgur.com/5AgkY2cg.jpg (all filled with green). Then the app hangs and moving the phone does not result in an updated preview.
I am using v.0.2.3 of advanced camera.

**Comment by bonanza123** [comment]
The problem seems to be related to a (wrong) resolution set in advanced camera.

**Comment by piggz** [comment]
ah yes, that can happen .... what was the resolution, and i wonder why your device claimed to support it

**Comment by piggz** [comment]
ah yes, that can happen .... what was the resolution, and i wonder why your device claimed to support it

**Comment by bonanza123** [comment]
In one of the previous version, I selected the highest resolution possible. This resolution seems to have been saved also after upgrading. Now I just selected the now available max. resolution and it worked.
Maybe the whole is obsolete now because the highest offered resolution is working fine.
