### ISSUE TITLE
Clarifying the license term

### ISSUE THREAD

**Issue by peat-psuwit** [piggz/harbour-advanced-camera#64]
I'm trying to find out what license is applied to the code. According to the LICENSE file, it seems like the license is GPLv2. However, each source code doesn't have the copyright notice (the "This program is free software...." thing). So, I'm not sure if every file is licensed under GPLv2 and, more importantly, if it's available under GPLv3 or later too.

I'm trying to copy a part of this program into another program which is licensed under GPLv3, so it's important to know for sure whether the license is GPLv2 or GPLv2+.

**Comment by piggz** [comment]
out of interest, what r u copying into?

**Comment by peat-psuwit** [comment]
I'm going to copy [the viewfinder resolution handling](https://github.com/piggz/harbour-advanced-camera/blob/7c486c7decd8bf8d4ff6ac86c2058f88587dd7d6/qml/pages/CameraUI.qml#L373) into [UBports' camera-app](https://gitlab.com/ubports/apps/camera-app) which is licensed as GPLv3 only. 

I'm a bit pedantic when it comes to licensing, so if you confirm that the code is GPLv2 only I'll have to re-implement it myself, looking only what API is used from your code. But if the code is GPLv2+ or GPLv3 I can re-use your implementation as-is or with modification. [GPLv2 is incompatible with GPLv3](https://opensource.stackexchange.com/a/1778), so FSF encourages people to allow the later versions of the license.

To make your decision clear, I also encourage you to add license notice on top of every source file. [Look here](https://www.gnu.org/licenses/gpl-howto.en.html) for how you can do that.

**Comment by piggz** [comment]
i have no issue making the app v2+, i will just have to do some due diligence and contact as many contributors as possible, esp the author of that code.  So long as everyine is happy, i will add proper licenses to all files.

i do note though, that you have chosen v3 only for ubports, so the argument could be made that you could also relicense to allow either (a hypothetical) gplv4 licensed app to use your code, or, v2 apps ;)

**Comment by peat-psuwit** [comment]
Well, the license choice is not ours. The code is inherited from Canonical, thus it's their choice. Anyway, you could also leave it as GPLv2 only if it's easier for you. After looking at the code in detail, it seems like I will not be able to reuse the code as much as I thought. So, I'm sorry if this becomes the noise for you. I still encourage you to put the license notice though. :)

**Comment by piggz** [comment]
LICENSE file is added
