### ISSUE TITLE
SD card support missing

### ISSUE THREAD

**Issue by teleshoes** [piggz/harbour-advanced-camera#77]
fully configurable paths would be nice, but just a toggle for `/media/sdcard/*` instead of `~/` would be on par with SFOS cam.

i assume this feature is intended, i just didnt see it actually mentioned anywhere.

p.s.: awesome app! IMO, already better than stock in every way, except the above

**Comment by vknecht** [comment]
Began working on it with #78

**Comment by teleshoes** [comment]
woo!
