### ISSUE TITLE
First option from menus at the top of the screen is too close to screen border.

### ISSUE THREAD

**Issue by atlochowski** [piggz/harbour-advanced-camera#79]
When I tap on flash icon, menu opening and first option is to close to the screen border. This happening with all menus.
I can't send screenshot because screenshot shortcut doesn't work with your app.

**Comment by raketti** [comment]
Seems to affect only portrait mode in XA2 (H4113).

**Comment by atlochowski** [comment]
> Seems to affect only portrait mode in XA2 (H4113).

Yes I just notice that and wanted to write about that but you were faster than me :)

**Comment by mlehtima** [comment]
This seems to affect also other devices and indeed only in portrait mode.

**Comment by mlehtima** [comment]
I'll have a look at fixing the issue

**Comment by piggz** [comment]
Fixed in 0.6.1
